server:
  port: 8903
  servlet:
    context-path: /


info:
  app.name: caiwu-baobiao
  app.info: 财务报表
  version: "1.0"
  author: "李道明"


spring:
  application:
    name: caiwu-baobiao
    info: 财务报表

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

  datasource:
    dynamic:
      datasource:

        # 默认效益测算的数据库
        master:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@localhost:1521/xe
          username: 效益测算
          password: abc123


        # 价格表的数据库
        jiaGe:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@localhost:1521/xe
          username: 效益测算
          password: abc123


  #静态资源
  mvc:
    static-path-pattern: /**
    date-format: yyyy-MM-dd
    throw-exception-if-no-handler-found: true

  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss SSS
    time-zone: GMT+8

  jmx:
    enabled: false

  http:
    encoding:
      charset: utf-8

  servlet:
    multipart:
      max-file-size: 20Mb


mybatis-plus:
  mapper-locations: classpath:com/hzsh/*/mapper/*Mapper.xml
  type-aliases-package: com.hzsh.*.model.*

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl